// <auto-generated />
using System;
using ArtAuction.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtAuction.Migrations
{
    [DbContext(typeof(ArtAuctionDbContext))]
    [Migration("20250922060158_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtAuction.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AuctionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuctionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtworkId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ArtistId = 2,
                            AuctionEndTime = new DateTime(2025, 9, 26, 0, 6, 45, 214, DateTimeKind.Local),
                            AuctionStartTime = new DateTime(2025, 9, 21, 0, 6, 45, 213, DateTimeKind.Local),
                            Category = "Painting",
                            Description = "Acrylic on canvas",
                            ImageUrl = "/images/sunsetimage.jpeg",
                            StartingPrice = 1000m,
                            Title = "Sunset Painting"
                        });
                });

            modelBuilder.Entity("ArtAuction.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.HasKey("BidId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            BidId = 1,
                            ArtworkId = 1,
                            BidAmount = 1200m,
                            BidTime = new DateTime(2025, 9, 20, 23, 36, 45, 214, DateTimeKind.Local),
                            BuyerId = 3
                        });
                });

            modelBuilder.Entity("ArtAuction.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            ReceiptId = 1,
                            GeneratedOn = new DateTime(2025, 9, 21, 0, 6, 45, 215, DateTimeKind.Local),
                            PdfFilePath = "/receipts/txn_1.pdf",
                            TransactionId = 1
                        });
                });

            modelBuilder.Entity("ArtAuction.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            ArtworkId = 1,
                            BuyerId = 3,
                            FinalPrice = 1200m,
                            PaymentMethod = "UPI",
                            PaymentStatus = "Completed",
                            TransactionDate = new DateTime(2025, 9, 21, 0, 6, 45, 215, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("ArtAuction.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@auction.com",
                            FullName = "Admin ",
                            PasswordHash = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist1@auction.com",
                            FullName = "Artist1 ",
                            PasswordHash = "artist123",
                            Role = "Artist"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "buyer1@auction.com",
                            FullName = "Buyer1",
                            PasswordHash = "buyer123",
                            Role = "Buyer"
                        });
                });

            modelBuilder.Entity("ArtAuction.Models.Artwork", b =>
                {
                    b.HasOne("ArtAuction.Models.User", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtAuction.Models.Bid", b =>
                {
                    b.HasOne("ArtAuction.Models.Artwork", "Artwork")
                        .WithMany("Bids")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtAuction.Models.User", "Buyer")
                        .WithMany("Bids")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("ArtAuction.Models.Receipt", b =>
                {
                    b.HasOne("ArtAuction.Models.Transaction", "Transaction")
                        .WithOne("Receipt")
                        .HasForeignKey("ArtAuction.Models.Receipt", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ArtAuction.Models.Transaction", b =>
                {
                    b.HasOne("ArtAuction.Models.Artwork", "Artwork")
                        .WithMany("Transactions")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtAuction.Models.User", "Buyer")
                        .WithMany("Transactions")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("ArtAuction.Models.Artwork", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ArtAuction.Models.Transaction", b =>
                {
                    b.Navigation("Receipt")
                        .IsRequired();
                });

            modelBuilder.Entity("ArtAuction.Models.User", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("Bids");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
