// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillAssessmentPortal.Models;

#nullable disable

namespace SkillAssesmentPortal.Migrations
{
    [DbContext(typeof(SkillAssessmentDbContext))]
    partial class SkillAssessmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestLevelId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("TestLevelId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CorrectOption = "A",
                            OptionA = "Common Language Runtime",
                            OptionB = "Compile Language Runtime",
                            OptionC = "Code Logic Reader",
                            OptionD = "None of the above",
                            QuestionText = "What does CLR stand for in C#?",
                            TestLevelId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            CorrectOption = "C",
                            OptionA = "function",
                            OptionB = "define",
                            OptionC = "class",
                            OptionD = "structure",
                            QuestionText = "Which keyword is used to define a class in C#?",
                            TestLevelId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            CorrectOption = "D",
                            OptionA = "18",
                            OptionB = "20",
                            OptionC = "24",
                            OptionD = "32",
                            QuestionText = "Find the missing number: 2, 4, 8, 16, ?",
                            TestLevelId = 4
                        },
                        new
                        {
                            QuestionId = 4,
                            CorrectOption = "A",
                            OptionA = "Listening carefully",
                            OptionB = "Using complex words",
                            OptionC = "Talking loudly",
                            OptionD = "Interrupting others",
                            QuestionText = "Effective communication includes:",
                            TestLevelId = 7
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Technical",
                            Description = "Programming and Software"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Aptitude",
                            Description = "Logical and Quantitative Skills"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Soft Skills",
                            Description = "Communication and Behavioral Skills"
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<string>("CertificateURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CertificateId");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId", "TestId")
                        .IsUnique();

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            CertificateId = 1,
                            CertificateURL = "/certificates/student1_csharpfundamentals.pdf",
                            IssueDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAttempted")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Suggestion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("TestLevelId")
                        .HasColumnType("int");

                    b.Property<int>("TimeTakenSecs")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("TestId");

                    b.HasIndex("TestLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            ResultId = 1,
                            AttemptNumber = 1,
                            DateAttempted = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 85.50m,
                            ResultStatus = "Pass",
                            Score = 85.50m,
                            Suggestion = "Good job! Proceed to Medium level.",
                            TestId = 1,
                            TestLevelId = 1,
                            TimeTakenSecs = 1200,
                            UserId = 2
                        },
                        new
                        {
                            ResultId = 2,
                            AttemptNumber = 1,
                            DateAttempted = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 45.00m,
                            ResultStatus = "Fail",
                            Score = 45.00m,
                            Suggestion = "Need to improve logical reasoning.",
                            TestId = 2,
                            TestLevelId = 4,
                            TimeTakenSecs = 1300,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DurationMins")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            TestId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DurationMins = 30,
                            TestName = "C# Fundamentals",
                            TotalMarks = 100,
                            TotalQuestions = 15
                        },
                        new
                        {
                            TestId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DurationMins = 30,
                            TestName = "Logical Reasoning",
                            TotalMarks = 100,
                            TotalQuestions = 20
                        },
                        new
                        {
                            TestId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            DurationMins = 20,
                            TestName = "Communication Skills",
                            TotalMarks = 50,
                            TotalQuestions = 10
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.TestLevel", b =>
                {
                    b.Property<int>("TestLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestLevelId"));

                    b.Property<int>("DurationMins")
                        .HasColumnType("int");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("VideoLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TestLevelId");

                    b.HasIndex("TestId", "LevelName")
                        .IsUnique();

                    b.ToTable("TestLevels");

                    b.HasData(
                        new
                        {
                            TestLevelId = 1,
                            DurationMins = 0,
                            LevelName = "Easy",
                            PassingScore = 60.00m,
                            TestId = 1,
                            VideoLink = "https://www.youtube.com/watch?v=gfkTfcpWqAY"
                        },
                        new
                        {
                            TestLevelId = 2,
                            DurationMins = 0,
                            LevelName = "Medium",
                            PassingScore = 65.00m,
                            TestId = 1,
                            VideoLink = "https://www.youtube.com/watch?v=GhQdlIFylQ8"
                        },
                        new
                        {
                            TestLevelId = 3,
                            DurationMins = 0,
                            LevelName = "Hard",
                            PassingScore = 70.00m,
                            TestId = 1,
                            VideoLink = "https://www.youtube.com/watch?v=IYvD9oBCuJI"
                        },
                        new
                        {
                            TestLevelId = 4,
                            DurationMins = 0,
                            LevelName = "Easy",
                            PassingScore = 60.00m,
                            TestId = 2,
                            VideoLink = "https://www.youtube.com/watch?v=lX2U3R1HfN0"
                        },
                        new
                        {
                            TestLevelId = 5,
                            DurationMins = 0,
                            LevelName = "Medium",
                            PassingScore = 65.00m,
                            TestId = 2,
                            VideoLink = "https://www.youtube.com/watch?v=QTY6lFQ0V7c"
                        },
                        new
                        {
                            TestLevelId = 6,
                            DurationMins = 0,
                            LevelName = "Hard",
                            PassingScore = 70.00m,
                            TestId = 2,
                            VideoLink = "https://www.youtube.com/watch?v=xEqlgNaJ1WA"
                        },
                        new
                        {
                            TestLevelId = 7,
                            DurationMins = 0,
                            LevelName = "Easy",
                            PassingScore = 55.00m,
                            TestId = 3,
                            VideoLink = "https://www.youtube.com/watch?v=HAnw168huqA"
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@portal.com",
                            Name = "Admin User",
                            PasswordHash = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student1@portal.com",
                            Name = "Student One",
                            PasswordHash = "student123",
                            Role = "User"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student2@portal.com",
                            Name = "Student Two",
                            PasswordHash = "student123",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.UserAnswer", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAnswerId"));

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("UserAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("SkillAssessmentPortal.Models.TestLevel", "TestLevel")
                        .WithMany("Questions")
                        .HasForeignKey("TestLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestLevel");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Certificate", b =>
                {
                    b.HasOne("SkillAssessmentPortal.Models.Test", "Test")
                        .WithMany("Certificates")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillAssessmentPortal.Models.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Result", b =>
                {
                    b.HasOne("SkillAssessmentPortal.Models.Test", "Test")
                        .WithMany("Results")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillAssessmentPortal.Models.TestLevel", "TestLevel")
                        .WithMany("Results")
                        .HasForeignKey("TestLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillAssessmentPortal.Models.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("TestLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Test", b =>
                {
                    b.HasOne("SkillAssessmentPortal.Models.Category", "Category")
                        .WithMany("Tests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillAssessmentPortal.Models.User", "AdminUser")
                        .WithMany("CreatedTests")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.TestLevel", b =>
                {
                    b.HasOne("SkillAssessmentPortal.Models.Test", "Test")
                        .WithMany("Levels")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.UserAnswer", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillAssessmentPortal.Models.Result", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Category", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.Test", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Levels");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.TestLevel", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("SkillAssessmentPortal.Models.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CreatedTests");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
